resources:
  repositories:
  - repository: PipelineRepo
    type: git
    ref: master
    name: <PROJETO>/devops-templates

trigger:
  branches:
    include:
      - refs/heads/dev
  paths:
    include:
    - src/WebResources

pool:
  vmImage: windows-latest

variables:
- group: powerplatform-variable-group

stages:
- stage: export_solution
  displayName: 'Export solution'
  
  jobs:
  - job: export_solution

    pool:
      vmImage: windows-latest

    steps:
    - pwsh: |
        # Workaround for git Filename too long issue
        git config --system core.longpaths true
      displayName: "Configuring core.longpaths true"

    # Checkout Pipelines
    - checkout: git://$(System.TeamProject)/devops-templates@master
      path: 'PipelineUtils'
      displayName: 'Checkout Pipeline Branch'
    
    # Checkout Solution
    - checkout: self
      persistCredentials: true
      displayName: 'Checkout Source Branch'

    - template: Templates/build-webresource.yml@PipelineRepo
      parameters:
        SolutionName: '<NOMELOGICOSOLUCAO>'
        Branch: 'dev'
        DevServiceConnectionName: $(DevServiceConnectionName)
        DevServiceConnectionURL: $(DevServiceConnectionURL)